import type {
  ProviderBackendConfig,
  ProviderDefinition,
  ProviderType,
  ProviderTypeInfo,
} from './types';

export const PROVIDER_DEFINITIONS: ProviderDefinition[] = [
  {
    id: 'anthropic',
    name: 'Anthropic',
    icon: '🤖',
    placeholder: 'sk-ant-api03-...',
    model: 'Claude',
    requiresApiKey: true,
    category: 'official',
    envVar: 'ANTHROPIC_API_KEY',
    defaultModelId: 'claude-opus-4-6',
    showModelId: true,
    modelIdPlaceholder: 'claude-opus-4-6',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    icon: '💚',
    placeholder: 'sk-proj-...',
    model: 'GPT',
    requiresApiKey: true,
    category: 'official',
    envVar: 'OPENAI_API_KEY',
    defaultModelId: 'gpt-5.5',
    isOAuth: true,
    supportsApiKey: true,
    showModelId: true,
    modelIdPlaceholder: 'gpt-5.5',
    supportedAuthModes: ['api_key', 'oauth_browser'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.openai.com/v1',
      api: 'openai-responses',
      apiKeyEnv: 'OPENAI_API_KEY',
    },
  },
  {
    id: 'google',
    name: 'Google',
    icon: '🔷',
    placeholder: 'AIza...',
    model: 'Gemini',
    requiresApiKey: true,
    category: 'official',
    envVar: 'GEMINI_API_KEY',
    defaultModelId: 'gemini-3.1-pro-preview',
    showModelId: true,
    modelIdPlaceholder: 'gemini-3.1-pro-preview',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: '🌐',
    placeholder: 'sk-or-v1-...',
    model: 'Multi-Model',
    requiresApiKey: true,
    showModelId: true,
    modelIdPlaceholder: 'anthropic/claude-opus-4.6',
    defaultModelId: 'anthropic/claude-opus-4.6',
    category: 'compatible',
    envVar: 'OPENROUTER_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://openrouter.ai/api/v1',
      api: 'openai-completions',
      apiKeyEnv: 'OPENROUTER_API_KEY',
      headers: {
        'HTTP-Referer': 'https://claw-x.com',
        'X-OpenRouter-Title': 'ClawDock',
      },
    },
  },
  {
    id: 'ark',
    name: 'ByteDance Ark',
    icon: 'A',
    placeholder: 'your-ark-api-key',
    model: 'Doubao',
    requiresApiKey: true,
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'ep-20260228000000-xxxxx',
    category: 'official',
    envVar: 'ARK_API_KEY',
    codePlanPresetBaseUrl: 'https://ark.cn-beijing.volces.com/api/coding/v3',
    codePlanPresetModelId: 'ark-code-latest',
    codePlanDocsUrl: 'https://www.volcengine.com/docs/82379/1928261?lang=zh',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
      api: 'openai-completions',
      apiKeyEnv: 'ARK_API_KEY',
    },
  },
  {
    id: 'kimi-coding',
    name: 'Kimi Coding',
    icon: '🌙',
    placeholder: 'sk-...',
    model: 'Kimi Code',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.kimi.com/coding/',
    defaultModelId: 'kimi-code',
    category: 'official',
    envVar: 'KIMI_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.kimi.com/coding/',
      api: 'anthropic-messages',
      apiKeyEnv: 'KIMI_API_KEY',
      headers: { 'User-Agent': 'claude-code/0.1.0' },
      models: [
        {
          id: 'kimi-code',
          name: 'Kimi Code',
          reasoning: true,
          input: ['text', 'image'],
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
          contextWindow: 262144,
          maxTokens: 32768,
        },
        {
          id: 'k2p5',
          name: 'Kimi Code (legacy)',
          reasoning: true,
          input: ['text', 'image'],
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
          contextWindow: 262144,
          maxTokens: 32768,
        },
      ],
    },
  },
  {
    id: 'moonshot',
    name: 'Moonshot (CN)',
    icon: '🌙',
    placeholder: 'sk-...',
    model: 'Kimi',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.moonshot.cn/v1',
    defaultModelId: 'kimi-k2.6',
    showModelId: true,
    modelIdPlaceholder: 'kimi-k2.6',
    category: 'official',
    envVar: 'MOONSHOT_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.moonshot.cn/v1',
      api: 'openai-completions',
      apiKeyEnv: 'MOONSHOT_API_KEY',
      models: [
        {
          id: 'kimi-k2.6',
          name: 'Kimi K2.6',
          reasoning: false,
          input: ['text'],
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
          contextWindow: 256000,
          maxTokens: 8192,
        },
      ],
    },
  },
  {
    id: 'moonshot-global',
    name: 'Moonshot (Global)',
    icon: '🌙',
    placeholder: 'sk-...',
    model: 'Kimi',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.moonshot.ai/v1',
    defaultModelId: 'kimi-k2.6',
    showModelId: true,
    modelIdPlaceholder: 'kimi-k2.6',
    category: 'official',
    envVar: 'MOONSHOT_GLOBAL_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.moonshot.ai/v1',
      api: 'openai-completions',
      apiKeyEnv: 'MOONSHOT_GLOBAL_API_KEY',
      models: [
        {
          id: 'kimi-k2.6',
          name: 'Kimi K2.6',
          reasoning: false,
          input: ['text'],
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
          contextWindow: 256000,
          maxTokens: 8192,
        },
      ],
    },
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow (CN)',
    icon: '🌊',
    placeholder: 'sk-...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.siliconflow.cn/v1',
    showModelId: true,
    modelIdPlaceholder: 'deepseek-ai/DeepSeek-V3',
    defaultModelId: 'deepseek-ai/DeepSeek-V3',
    category: 'compatible',
    envVar: 'SILICONFLOW_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.siliconflow.cn/v1',
      api: 'openai-completions',
      apiKeyEnv: 'SILICONFLOW_API_KEY',
    },
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    icon: '🐋',
    placeholder: 'sk-...',
    model: 'DeepSeek',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.deepseek.com/v1',
    showModelId: true,
    modelIdPlaceholder: 'deepseek-v4-pro',
    defaultModelId: 'deepseek-v4-pro',
    apiKeyUrl: 'https://platform.deepseek.com/api_keys',
    category: 'official',
    envVar: 'DEEPSEEK_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.deepseek.com/v1',
      api: 'openai-completions',
      apiKeyEnv: 'DEEPSEEK_API_KEY',
    },
  },
  {
    id: 'minimax-portal',
    name: 'MiniMax (Global)',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'MiniMax',
    requiresApiKey: false,
    isOAuth: true,
    supportsApiKey: true,
    defaultModelId: 'MiniMax-M2.7',
    showModelId: true,
    modelIdPlaceholder: 'MiniMax-M2.7',
    apiKeyUrl: 'https://platform.minimax.io',
    category: 'official',
    envVar: 'MINIMAX_API_KEY',
    supportedAuthModes: ['oauth_device', 'api_key'],
    defaultAuthMode: 'oauth_device',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.minimax.io/anthropic',
      api: 'anthropic-messages',
      apiKeyEnv: 'MINIMAX_API_KEY',
    },
  },
  {
    id: 'minimax-portal-cn',
    name: 'MiniMax (CN)',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'MiniMax',
    requiresApiKey: false,
    isOAuth: true,
    supportsApiKey: true,
    defaultModelId: 'MiniMax-M2.7',
    showModelId: true,
    modelIdPlaceholder: 'MiniMax-M2.7',
    apiKeyUrl: 'https://platform.minimaxi.com/',
    category: 'official',
    envVar: 'MINIMAX_CN_API_KEY',
    supportedAuthModes: ['oauth_device', 'api_key'],
    defaultAuthMode: 'oauth_device',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.minimaxi.com/anthropic',
      api: 'anthropic-messages',
      apiKeyEnv: 'MINIMAX_CN_API_KEY',
    },
  },
  {
    id: 'modelstudio',
    name: 'Model Studio',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'Qwen',
    requiresApiKey: true,
    defaultBaseUrl: 'https://coding.dashscope.aliyuncs.com/v1',
    showBaseUrl: true,
    defaultModelId: 'qwen3.6-plus',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'qwen3.6-plus',
    category: 'official',
    envVar: 'MODELSTUDIO_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://coding.dashscope.aliyuncs.com/v1',
      api: 'openai-completions',
      apiKeyEnv: 'MODELSTUDIO_API_KEY',
    },
  },
  {
    id: 'qwen-coding-cn',
    name: 'Qwen Coding (CN)',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'Qwen',
    requiresApiKey: true,
    defaultBaseUrl: 'https://coding.dashscope.aliyuncs.com/v1',
    showBaseUrl: true,
    defaultModelId: 'qwen3.5-plus',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'qwen3.5-plus',
    category: 'official',
    envVar: 'MODELSTUDIO_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://coding.dashscope.aliyuncs.com/v1',
      api: 'openai-completions',
      apiKeyEnv: 'MODELSTUDIO_API_KEY',
      models: [
        { id: 'qwen3.5-plus', name: 'qwen3.5-plus', reasoning: false, input: ['text', 'image'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65536 },
        { id: 'qwen3.6-plus', name: 'qwen3.6-plus', reasoning: false, input: ['text', 'image'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65536 },
        { id: 'qwen3-max-2026-01-23', name: 'qwen3-max-2026-01-23', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 65536 },
        { id: 'qwen3-coder-next', name: 'qwen3-coder-next', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 65536 },
        { id: 'qwen3-coder-plus', name: 'qwen3-coder-plus', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65536 },
      ],
    },
  },
  {
    id: 'qwen-standard-global',
    name: 'Qwen Standard (Global)',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'Qwen',
    requiresApiKey: true,
    defaultBaseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    showBaseUrl: true,
    defaultModelId: 'qwen3.5-plus',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'qwen3.5-plus',
    category: 'official',
    envVar: 'QWEN_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
      api: 'openai-completions',
      apiKeyEnv: 'QWEN_API_KEY',
      models: [
        { id: 'qwen3.5-plus', name: 'qwen3.5-plus', reasoning: false, input: ['text', 'image'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65536 },
        { id: 'qwen3.6-plus', name: 'qwen3.6-plus', reasoning: false, input: ['text', 'image'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65536 },
        { id: 'qwen3-max-2026-01-23', name: 'qwen3-max-2026-01-23', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 65536 },
        { id: 'qwen3-coder-next', name: 'qwen3-coder-next', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 65536 },
        { id: 'qwen3-coder-plus', name: 'qwen3-coder-plus', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65536 },
        { id: 'MiniMax-M2.5', name: 'MiniMax-M2.5', reasoning: true, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65536 },
        { id: 'glm-5', name: 'glm-5', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 202752, maxTokens: 16384 },
        { id: 'glm-4.7', name: 'glm-4.7', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 202752, maxTokens: 16384 },
        { id: 'kimi-k2.5', name: 'kimi-k2.5', reasoning: false, input: ['text', 'image'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 32768 },
      ],
    },
  },
  {
    id: 'qwen-standard-cn',
    name: 'Qwen Standard (CN)',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'Qwen',
    requiresApiKey: true,
    defaultBaseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    showBaseUrl: true,
    defaultModelId: 'qwen3.5-plus',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'qwen3.5-plus',
    category: 'official',
    envVar: 'QWEN_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
      api: 'openai-completions',
      apiKeyEnv: 'QWEN_API_KEY',
      models: [
        { id: 'qwen3.5-plus', name: 'qwen3.5-plus', reasoning: false, input: ['text', 'image'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65536 },
        { id: 'qwen3.6-plus', name: 'qwen3.6-plus', reasoning: false, input: ['text', 'image'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65536 },
        { id: 'qwen3-max-2026-01-23', name: 'qwen3-max-2026-01-23', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 65536 },
        { id: 'qwen3-coder-next', name: 'qwen3-coder-next', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 65536 },
        { id: 'qwen3-coder-plus', name: 'qwen3-coder-plus', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65536 },
        { id: 'MiniMax-M2.5', name: 'MiniMax-M2.5', reasoning: true, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65536 },
        { id: 'glm-5', name: 'glm-5', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 202752, maxTokens: 16384 },
        { id: 'glm-4.7', name: 'glm-4.7', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 202752, maxTokens: 16384 },
        { id: 'kimi-k2.5', name: 'kimi-k2.5', reasoning: false, input: ['text', 'image'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 32768 },
      ],
    },
  },
  {
    id: 'zai',
    name: 'Z.AI (GLM)',
    icon: '🔷',
    placeholder: 'sk-...',
    model: 'GLM',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.z.ai/v1',
    showBaseUrl: true,
    defaultModelId: 'glm-5',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'glm-5',
    category: 'official',
    envVar: 'ZAI_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.z.ai/v1',
      api: 'openai-completions',
      apiKeyEnv: 'ZAI_API_KEY',
      models: [
        { id: 'glm-5', name: 'glm-5', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 202752, maxTokens: 16384 },
        { id: 'glm-4.7', name: 'glm-4.7', reasoning: false, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 202752, maxTokens: 16384 },
      ],
    },
  },
  {
    id: 'stepfun',
    name: 'Stepfun',
    icon: '📶',
    placeholder: 'sk-...',
    model: 'Step',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.stepfun.com/v1',
    showBaseUrl: true,
    defaultModelId: 'step-3.5-flash',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'step-3.5-flash',
    category: 'official',
    envVar: 'STEPFUN_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.stepfun.com/v1',
      api: 'openai-completions',
      apiKeyEnv: 'STEPFUN_API_KEY',
      models: [
        { id: 'step-3.5-flash', name: 'Step 3.5 Flash', reasoning: true, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 65536 },
      ],
    },
  },
  {
    id: 'stepfun-plan',
    name: 'Stepfun Plan',
    icon: '📶',
    placeholder: 'sk-...',
    model: 'Step',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.stepfun.com/step_plan/v1',
    showBaseUrl: true,
    defaultModelId: 'step-3.5-flash',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'step-3.5-flash',
    category: 'official',
    envVar: 'STEPFUN_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.stepfun.com/step_plan/v1',
      api: 'openai-completions',
      apiKeyEnv: 'STEPFUN_API_KEY',
      models: [
        { id: 'step-3.5-flash', name: 'Step 3.5 Flash', reasoning: true, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 65536 },
        { id: 'step-3.5-flash-2603', name: 'Step 3.5 Flash 2603', reasoning: true, input: ['text'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 65536 },
      ],
    },
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    icon: 'X',
    placeholder: 'xai-...',
    model: 'Grok',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.x.ai/v1',
    defaultModelId: 'grok-4',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'grok-4',
    category: 'official',
    envVar: 'XAI_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.x.ai/v1',
      api: 'openai-responses',
      apiKeyEnv: 'XAI_API_KEY',
      models: [
        { id: 'grok-4', name: 'Grok 4', reasoning: true, input: ['text'], cost: { input: 3, output: 15, cacheRead: 0.75, cacheWrite: 0 }, contextWindow: 256000, maxTokens: 64000 },
        { id: 'grok-4-fast', name: 'Grok 4 Fast', reasoning: true, input: ['text', 'image'], cost: { input: 0.2, output: 0.5, cacheRead: 0.05, cacheWrite: 0 }, contextWindow: 2000000, maxTokens: 30000 },
        { id: 'grok-4.20-beta-latest-reasoning', name: 'Grok 4.20 Beta', reasoning: true, input: ['text', 'image'], cost: { input: 2, output: 6, cacheRead: 0.2, cacheWrite: 0 }, contextWindow: 2000000, maxTokens: 30000 },
        { id: 'grok-code-fast-1', name: 'Grok Code Fast 1', reasoning: true, input: ['text'], cost: { input: 0.2, output: 1.5, cacheRead: 0.02, cacheWrite: 0 }, contextWindow: 256000, maxTokens: 10000 },
      ],
    },
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    icon: '🌬️',
    placeholder: 'mistral-...',
    model: 'Mistral',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.mistral.ai/v1',
    defaultModelId: 'mistral-large-latest',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'mistral-large-latest',
    category: 'official',
    envVar: 'MISTRAL_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.mistral.ai/v1',
      api: 'openai-completions',
      apiKeyEnv: 'MISTRAL_API_KEY',
      models: [
        { id: 'mistral-large-latest', name: 'Mistral Large', reasoning: false, input: ['text', 'image'], cost: { input: 0.5, output: 1.5, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 16384 },
        { id: 'mistral-small-latest', name: 'Mistral Small', reasoning: true, input: ['text', 'image'], cost: { input: 0.1, output: 0.3, cacheRead: 0, cacheWrite: 0 }, contextWindow: 128000, maxTokens: 16384 },
        { id: 'codestral-latest', name: 'Codestral', reasoning: false, input: ['text'], cost: { input: 0.3, output: 0.9, cacheRead: 0, cacheWrite: 0 }, contextWindow: 256000, maxTokens: 4096 },
        { id: 'devstral-medium-latest', name: 'Devstral 2', reasoning: false, input: ['text'], cost: { input: 0.4, output: 2, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 32768 },
      ],
    },
  },
  {
    id: 'groq',
    name: 'Groq',
    icon: '⚡',
    placeholder: 'gsk_...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'llama-4-scout',
    defaultModelId: 'llama-4-scout',
    category: 'compatible',
    envVar: 'GROQ_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.groq.com/openai/v1',
      api: 'openai-completions',
      apiKeyEnv: 'GROQ_API_KEY',
    },
  },
  {
    id: 'together',
    name: 'Together AI',
    icon: '🤝',
    placeholder: 'together-...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.together.xyz/v1',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'meta-llama/Llama-4-Scout',
    defaultModelId: 'meta-llama/Llama-4-Scout',
    category: 'compatible',
    envVar: 'TOGETHER_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.together.xyz/v1',
      api: 'openai-completions',
      apiKeyEnv: 'TOGETHER_API_KEY',
      models: [
        { id: 'zai-org/GLM-4.7', name: 'GLM 4.7 FP8', reasoning: false, input: ['text'], cost: { input: 0.45, output: 2, cacheRead: 0.45, cacheWrite: 2 }, contextWindow: 202752, maxTokens: 8192 },
        { id: 'moonshotai/Kimi-K2.5', name: 'Kimi K2.5', reasoning: true, input: ['text', 'image'], cost: { input: 0.5, output: 2.8, cacheRead: 0.5, cacheWrite: 2.8 }, contextWindow: 262144, maxTokens: 32768 },
        { id: 'meta-llama/Llama-4-Scout-17B-16E-Instruct', name: 'Llama 4 Scout', reasoning: false, input: ['text', 'image'], cost: { input: 0.18, output: 0.59, cacheRead: 0.18, cacheWrite: 0.18 }, contextWindow: 10000000, maxTokens: 32768 },
        { id: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8', name: 'Llama 4 Maverick', reasoning: false, input: ['text', 'image'], cost: { input: 0.27, output: 0.85, cacheRead: 0.27, cacheWrite: 0.27 }, contextWindow: 20000000, maxTokens: 32768 },
        { id: 'deepseek-ai/DeepSeek-V3.1', name: 'DeepSeek V3.1', reasoning: false, input: ['text'], cost: { input: 0.6, output: 1.25, cacheRead: 0.6, cacheWrite: 0.6 }, contextWindow: 131072, maxTokens: 8192 },
        { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1', reasoning: true, input: ['text'], cost: { input: 3, output: 7, cacheRead: 3, cacheWrite: 3 }, contextWindow: 131072, maxTokens: 8192 },
      ],
    },
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    icon: '🎆',
    placeholder: 'fw-...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.fireworks.ai/inference/v1',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'accounts/fireworks/models/kimi-k2p6',
    defaultModelId: 'accounts/fireworks/models/kimi-k2p6',
    category: 'compatible',
    envVar: 'FIREWORKS_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.fireworks.ai/inference/v1',
      api: 'openai-completions',
      apiKeyEnv: 'FIREWORKS_API_KEY',
      models: [
        { id: 'accounts/fireworks/models/kimi-k2p6', name: 'Kimi K2.6', reasoning: false, input: ['text', 'image'], cost: { input: 0.95, output: 4, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 262144 },
        { id: 'accounts/fireworks/routers/kimi-k2p5-turbo', name: 'Kimi K2.5 Turbo', reasoning: false, input: ['text', 'image'], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 256000, maxTokens: 256000 },
      ],
    },
  },
  {
    id: 'ollama',
    name: 'Ollama',
    icon: '🦙',
    placeholder: 'Not required',
    requiresApiKey: false,
    defaultBaseUrl: 'http://localhost:11434/v1',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'qwen3:latest',
    category: 'local',
    supportedAuthModes: ['local'],
    defaultAuthMode: 'local',
    supportsMultipleAccounts: true,
  },
  {
    id: 'custom',
    name: 'Custom',
    icon: '⚙️',
    placeholder: 'API key...',
    requiresApiKey: true,
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'your-provider/model-id',
    category: 'custom',
    envVar: 'CUSTOM_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
];

const PROVIDER_DEFINITION_MAP = new Map(
  PROVIDER_DEFINITIONS.map((definition) => [definition.id, definition]),
);

export function getProviderDefinition(
  type: ProviderType | string,
): ProviderDefinition | undefined {
  return PROVIDER_DEFINITION_MAP.get(type as ProviderType);
}

export function getProviderTypeInfo(
  type: ProviderType,
): ProviderTypeInfo | undefined {
  return getProviderDefinition(type);
}

export function getProviderEnvVar(type: string): string | undefined {
  return getProviderDefinition(type)?.envVar;
}

export function getProviderDefaultModel(type: string): string | undefined {
  return getProviderDefinition(type)?.defaultModelId;
}

export function getProviderBackendConfig(
  type: string,
): ProviderBackendConfig | undefined {
  return getProviderDefinition(type)?.providerConfig;
}

export function getProviderUiInfoList(): ProviderTypeInfo[] {
  return PROVIDER_DEFINITIONS;
}

export function getKeyableProviderTypes(): string[] {
  return PROVIDER_DEFINITIONS.filter((definition) => definition.envVar).map(
    (definition) => definition.id,
  );
}
